# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - azdemo-db(int)

on:
  push:
    branches:
      - feature/deployment_slot_test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '8'

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v1
      with:
        app-name: 'azdemo-db(int)'
        slot-name: 'int'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4dba302c952146968353ef3feb49fad7 }}
        package: '${{ github.workspace }}/target/*.jar'